targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - test/**.browser_test.dart
        - web/**.dart
        options:
          compiler: dart2js
          dart2js_args:
          - --fast-startup
          - --csp