name: scraper
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://github.com/sanmadjack/parkingbrake
# author: downloading <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+11
  angular_components: ^0.9.0-alpha+11
  chrome: any
  logging: any
  logging_handlers: any
  uuid: any
  meta: any
  path: any
  html: any
  html_unescape: any
  sass: 1.3.2


dev_dependencies:
  angular_test: ^2.0.0-alpha+9
  angular_compiler: 0.4.0-alpha+11
  build_runner: ^0.8.7
  build_test: ^0.10.0
  build_web_compilers: ^0.3.7
  test: ^0.12.30


transformers:
- chrome