name: scraper
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: downloading <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  logging: any
  uuid: any
  meta: any
  path: any
  html: any
  stack_trace: any
  html_unescape: any
  js: any

dev_dependencies:
  angular_test: any
  angular_compiler: any
  build_runner: any
  build_test: any
  build_web_compilers: any
  test: any

